name: Divergence
favicon: null
layout_spectrum: 0.24393347022123635
typography_spectrum: 0.4827345691155642
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e2535'
    - '#5cb8cd'
    - '#5e7ea4'
    - '#c3d4de'
    - '#ffbe00'
  brandStrength: 0.9394174558110535
  lightness: 0.9250786325428635
  saturation: 0.9579853620380163
  rhythmicContrast: 0.3770378085318953
purpose: []
